//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaSemana
    {
        public long ID { get; set; }
        public System.DateTime DataDia { get; set; }
        public string NomeDia { get; set; }
        public int Semana { get; set; }
    }
}
