//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public long ReservaID { get; set; }
        public System.DateTime Presenca { get; set; }
        public long Matricula { get; set; }
        public long AulaID { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
